Created aim and process of project
bhattabhi013/Vritant pull request #23
Opened 2023-02-23 11:24 UTC by Bharadwajshivam28

created process and aim of project in readme file

2023-02-23 21:12 UTC, bhattabhi013 requested changes
Please do the suggested changes.

2023-02-23 21:12 UTC, bhattabhi013 commented on README.md
> +📌 Continuously improve the app's features, design, and functionality based on user <br>
This whole section is not customized for the application.
I suggest you run the application on your device or watch the demo for writing the workflow.

2023-02-23 21:12 UTC, bhattabhi013 commented on README.md
> +📌 We aim to incorporate features such 3D <br>
incomplete sentence.

2023-02-23 21:18 UTC, Bharadwajshivam28 commented
> Please do the suggested changes.

Ok sir

2023-02-24 14:03 UTC, Bharadwajshivam28 commented
@bhattabhi013 I have improved contents sir please look to it

2023-02-24 15:11 UTC, bhattabhi013 requested changes
Please resolve

2023-02-24 15:11 UTC, bhattabhi013 commented on README.md
> +📌 We have firstly identify the need of children like theri problems in studying <br>
their

2023-02-24 15:11 UTC, bhattabhi013 commented on README.md
> +📌 One can read the text and one can also play the text, as for kids reading one is hard so they can play the text also <br>
One can read the text and also play with it using text-to-speech functionality, as for kids reading one is hard so they can listen to the text as well.

2023-02-24 15:11 UTC, bhattabhi013 commented on README.md
> +📌 There is no paying of money to acess the app and features alsoas it is completely free <br>
There is no need to pay money as the app is free.

2023-02-24 15:16 UTC, Bharadwajshivam28 commented
> Please resolve

Ok sir

2023-02-24 15:59 UTC, Bharadwajshivam28 commented
@bhattabhi013 Corrected it sir

2023-02-24 16:23 UTC, bhattabhi013 approved these changes
LGTM

2023-02-24 16:23 UTC, merged

2023-02-24 16:23 UTC, Bharadwajshivam28 commented
please close the issue also sir